runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /style\.css
  static_files: style.css
  upload: style\.css

- url: /suit\.jpg
  static_files: suit.jpg
  upload: suit\.jpg

- url: /.*
  script: titlegen.app

libraries:
- name: webapp2
  version: latest
